---

---

```{r}
library(tidyverse)
library(geobr)
library(basedosdados)
library(sf)
library(cartogram)

afinidade <- read_csv("data/afinidade_ideologica.csv")
glimpse(afinidade)
```

```{r}
afinidade <- afinidade |>
  mutate(
    partido = as.factor(partido),
    label = as.factor(label)
  )
```


```{r}
df_all <- read_delim(
  "data/votacao_partido_munzona_2024_BRASIL.csv", 
  delim = ";", locale = locale(encoding = "latin1")
)
glimpse(df_all)
```


```{r}
df_prefeitos <- df_all |>
  filter(DS_CARGO == "Prefeito") |>
  mutate(
    uf = as.factor(SG_UF),
    partido = as.factor(SG_PARTIDO),
    id_municipio_tse = as.integer(CD_MUNICIPIO),
    QT_VOTOS_NOMINAIS_VALIDOS = as.integer(QT_VOTOS_NOMINAIS_VALIDOS),
    QT_VOTOS_NOMINAIS_ANUL_SUBJUD = as.integer(QT_VOTOS_NOMINAIS_ANUL_SUBJUD),
  ) |>
  group_by(NM_MUNICIPIO, uf, partido, id_municipio_tse) |>
  summarise(
    votos_nominais_validos = sum(QT_VOTOS_NOMINAIS_VALIDOS),
    votos_nominais_anul = sum(QT_VOTOS_NOMINAIS_ANUL_SUBJUD),
  ) |>
  group_by(NM_MUNICIPIO, uf) |>
  filter(dense_rank(desc(votos_nominais_validos)) == 1) # pegar o vencedor
```

```{r}
df_prefeitos |>
  count(NM_MUNICIPIO, uf, id_municipio_tse) |>
  arrange(desc(n))
```

Inhaúma teve um empate, [com o candidato do Republicanos ganhando pelo critério da idade](https://g1.globo.com/mg/minas-gerais/eleicoes/2024/noticia/2024/10/06/eleicao-em-inhauma-mg-termina-empatada-em-2434-x-2434-votos-entenda-como-vencedor-e-escolhido.ghtml).

```{r}
df_prefeitos <- df_prefeitos |> filter(id_municipio_tse != 46191 | partido == "REPUBLICANOS")
```


```{r}
# link tse-ibge by basedosdados
query <- "
SELECT
    dados.id_municipio as id_municipio,
    dados.id_municipio_tse as id_municipio_tse
FROM `basedosdados.br_bd_diretorios_brasil.municipio` AS dados
"

df_ibge_tse <- read_sql(query, billing_project_id = get_billing_id())
```


```{r}
df_ibge_tse <- df_ibge_tse |>
  mutate(
    id_municipio = as.integer(id_municipio),
    id_municipio_tse = as.integer(id_municipio_tse),
  )
head(df_ibge_tse)
```

Checar nulos:

```{r}
df_prefeitos |>
  left_join(df_ibge_tse, by = join_by(id_municipio_tse)) |>
  filter(is.na(id_municipio))
```

[Boa Esperança do Norte é um município novo](https://g1.globo.com/mt/mato-grosso/noticia/2023/10/13/conheca-boa-esperanca-do-norte-e-saiba-o-que-tem-no-novo-municipio-de-mt.ghtml) que não deve ter entrado na base do IBGE. Não haverá muito problema removê-lo da análise pois ele não possui código IBGE e, portanto, não haverá match no shapefile.

```{r}
df_prefeitos_ibge <- df_prefeitos |>
  left_join(df_ibge_tse, by = join_by(id_municipio_tse)) |>
  filter(!is.na(id_municipio))
```

Finalmente, o shapefile dos municípios brasileiros:

```{r}
mun <- read_municipality(code_muni = "all", year = 2022, simplified = T)
glimpse(mun)
```


```{r}
mun_votos <- mun |>
  mutate(code_muni = as.integer(code_muni)) |>
  left_join(df_prefeitos_ibge, by = join_by(code_muni == id_municipio)) |>
  select(code_muni, name_muni, uf, votos_nominais_validos, partido)
glimpse(mun_votos)
```


```{r}
mun_votos |> 
  distinct(partido)
```


```{r}
mun_votos <- mun_votos |>
  left_join(afinidade, by = join_by(partido)) |>
  select(code_muni:partido, label, geom)
glimpse(mun_votos)
```

```{r}
mun_votos |> filter(is.na(label))
```


Plotando

```{r, fig.align='center', fig.width=18}
mapa_cor_label = c(
  "esquerda_1" = "#b5000f",
  "esquerda_2" = "#fc0c20",
  "esquerda_3" = "#fc5f6c",
  "centro_1" = "#8ACE00",
  "centro_2" = "#13D626",
  "centro_3" = "#18BC4F",
  "direita_1" = "#2C5EF4",
  "direita_2" = "#0C19D1",
  "direita_3" = "#010CA0"
)

mun_votos |>
  ggplot(mapping = aes(fill = label)) +
  geom_sf(color="#FEBF57") +
  labs(title = "Municípios do Brasil por cluster de afinidade política nas votações de primeiro turno para prefeito (2024)") +
  scale_fill_manual(values = mapa_cor_label)
```

Gerando um cartograma

```{r}
mun_votos_cart <- mun_votos |>
  filter(!is.na(partido)) |>
  st_transform(crs = 31970) |>
  cartogram_dorling(weight = "votos_nominais_validos", m_weight = 1, itermax=20)
```

```{r, fig.align='center', fig.width=20}
mun_votos_cart |>
  ggplot(mapping = aes(fill = label)) +
  geom_sf(color="#FEBF57") +
  labs(title = "Municípios do Brasil por cluster de afinidade política nas votações de primeiro turno para prefeito (2024)") +
  scale_fill_manual(values = mapa_cor_label)
```


```{r}
mun_sp <- read_municipality("SP", year = 2022, simplified = T) |>
  mutate(code_muni = as.integer(code_muni)) |>
  left_join(df_prefeitos_ibge, by = join_by(code_muni == id_municipio)) |>
  select(code_muni, name_muni, uf, votos_nominais_validos, partido) |>
  left_join(afinidade, by = join_by(partido)) |>
  select(code_muni:partido, label, geom)
```

```{r}
mun_sp_cart <- mun_sp |>
  st_transform(31970) |>
  cartogram_cont(weight = "votos_nominais_validos", itermax=10)
```

```{r, fig.align='center', fig.width=20}
mun_sp_cart |>
  ggplot(mapping = aes(fill = label)) +
  geom_sf(color="#FEBF57") +
  labs(title = "Municípios de São Paulo por cluster de afinidade política nas votações de primeiro turno para prefeito (2024)") +
  scale_fill_manual(values = mapa_cor_label)
```


